# vim: ft=ansible
#
# usage:
#
#    ansible-playbook -i <path/to/inventory> update_hosts.yml --ask-become-pass
#
#
- hosts: servers
  gather_facts: no
  sudo: yes
  connection: local
  tasks:
  - name: "Build hosts file"
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ inventory_hostname }}$'
      line: "{{ ansible_host }} {{ inventory_hostname }}"
      state: present
    delegate_to: localhost
