---
- name: Deploy LAMP
  hosts: servers
  become: yes

  tasks:
    - name: Update package cache and install required packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - mariadb-server
        - php


    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install Hello World PHP script with database
      copy: src=index.php dest=/var/www/html/index.php mode=0664
