---
- name: Manage users and their logins
  hosts: servers  

  tasks:
    - name: Read user data from CSV
      read_csv:
        path: "/root/ansible/task2/user.csv" # Replace this path with your file
        delimiter: ","
      register: users_data

    - name: Create or update users
      become: true
      user:
        name: "{{ item.User }}"

        comment: "{{ item.Comment }}, {{item['Owner-Team']}}, {{ item.Functional}} "
        state: "{{ 'present' if item.User != 'username' else 'absent' }}"
      with_items: "{{ users_data.list }}"

    - name: Set up SSH authorized keys
      become: true
      authorized_key:
        user: "{{ item.User }}"
        key: "{{item['Pub-key']}}" # Provide the path to your public key
      with_items: "{{ users_data.list }}"
      when: item.User != 'username'  
